"""add satata migrations table

Revision ID: b738fa894aae
Revises: c36b96910d92
Create Date: 2026-01-29 11:04:04.071773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b738fa894aae'
down_revision: Union[str, None] = 'c36b96910d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrations_satata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False, comment='Migration name'),
    sa.Column('description', sa.String(length=2500), nullable=False, comment='Migration description'),
    sa.Column('executed', sa.Boolean(), nullable=False, comment='Whether the migration was executed or not'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "INSERT INTO migrations_satata (name, description, executed) VALUES "
        "('migration_1', 'Insert canonical activity types from activity utils.', false)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrations_satata')
    # ### end Alembic commands ###
