"""create tables required for insights

Revision ID: c36b96910d92
Revises: 7642476ff9e0
Create Date: 2026-01-28 14:18:43.321585

"""
from typing import Sequence, Union

from sqlalchemy.dialects.postgresql import ARRAY, JSONB

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b96910d92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('satata',)
depends_on: Union[str, Sequence[str], None] = '262ec21a6c15'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Activity category ID'),
    sa.Column('name', sa.String(length=250), nullable=False, comment='Internal activity category name (e.g. easy, tempo, long)'),
    sa.Column('display_name', sa.String(length=250), nullable=False, comment='User-facing activity category name (e.g. Easy, Tempo, Long)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_categories_name'), 'activity_categories', ['name'], unique=True)
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Activity type ID'),
    sa.Column('name', sa.String(length=250), nullable=False, comment='Internal activity type name (e.g. run, ride, swim)'),
    sa.Column('display_name', sa.String(length=250), nullable=False, comment='User-facing activity type name (e.g. Run, Ride, Swim)'),
    sa.Column('ai_insight_parameters', ARRAY(sa.String()), nullable=True, comment='List of parameter that considered for ai insights generation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_types_name'), 'activity_types', ['name'], unique=True)
    op.create_table('user_category_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='User category rule ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID this rule belongs to'),
    sa.Column('activity_type_id', sa.Integer(), nullable=False, comment='Activity type ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Activity category ID'),
    sa.Column('values', JSONB(), nullable=False, comment='JSON object defining the rule values'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Rule creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Rule last update timestamp'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_category_rules_activity_type_id'), 'user_category_rules', ['activity_type_id'], unique=False)
    op.create_index(op.f('ix_user_category_rules_category_id'), 'user_category_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_user_category_rules_user_id'), 'user_category_rules', ['user_id'], unique=False)
    op.create_table('user_activity_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='User activity statistics ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('activity_type_id', sa.Integer(), nullable=False, comment='Activity type ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Activity category ID'),
    sa.Column('avg_distance', sa.Float(), nullable=True, comment='Average distance in meters'),
    sa.Column('m2_distance', sa.Float(), nullable=True, comment='Welford M2 value for distance variance'),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True, comment='Average heart rate'),
    sa.Column('m2_heart_rate', sa.Float(), nullable=True, comment='Welford M2 value for heart rate variance'),
    sa.Column('avg_pace', sa.Float(), nullable=True, comment='Average pace in seconds per kilometer'),
    sa.Column('m2_pace', sa.Float(), nullable=True, comment='Welford M2 value for pace variance'),
    sa.Column('avg_duration', sa.Float(), nullable=True, comment='Average moving time in seconds'),
    sa.Column('m2_duration', sa.Float(), nullable=True, comment='Welford M2 value for duration variance'),
    sa.Column('avg_elevation_gain', sa.Float(), nullable=True, comment='Average elevation gain in meters'),
    sa.Column('m2_elevation_gain', sa.Float(), nullable=True, comment='Welford M2 value for elevation gain variance'),
    sa.Column('avg_elevation_loss', sa.Float(), nullable=True, comment='Average elevation loss in meters'),
    sa.Column('m2_elevation_loss', sa.Float(), nullable=True, comment='Welford M2 value for elevation loss variance'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='Total number of activities in this category'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last statistics update timestamp'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ),
    sa.UniqueConstraint('user_id', 'activity_type_id', 'category_id', name='uq_user_activity_stats_bucket'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_stats_user_id'), 'user_activity_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_stats_activity_type_id'), 'user_activity_stats', ['activity_type_id'], unique=False)
    op.create_index(op.f('ix_user_activity_stats_category_id'), 'user_activity_stats', ['category_id'], unique=False)
    op.create_table('activity_ai_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='AI insight record ID'),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='Activity ID this AI insight belongs to'),
    sa.Column('insight_text', sa.Text(), nullable=True, comment='Generated AI insight text for the activity'),
    sa.Column('model_used', sa.String(length=250), nullable=True, comment='LLM model used to generate the insight'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Insight creation timestamp'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_ai_insights_activity_id'), 'activity_ai_insights', ['activity_id'], unique=False)
    op.create_table('activity_delta_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Activity delta record ID'),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='Activity ID this delta record belongs to'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('activity_type_id', sa.Integer(), nullable=False, comment='Activity type ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Activity category ID'),
    sa.Column('delta_distance', sa.Float(), nullable=True, comment='Delta distance in meters compared to baseline average'),
    sa.Column('delta_distance_pct', sa.Float(), nullable=True, comment='Delta distance percentage compared to baseline average'),
    sa.Column('delta_hr', sa.Float(), nullable=True, comment='Delta average heart rate compared to baseline'),
    sa.Column('delta_hr_pct', sa.Float(), nullable=True, comment='Delta heart rate percentage compared to baseline'),
    sa.Column('delta_avg_pace', sa.Float(), nullable=True, comment='Delta average pace (sec/km) compared to baseline'),
    sa.Column('delta_avg_pace_pct', sa.Float(), nullable=True, comment='Delta average pace percentage compared to baseline'),
    sa.Column('delta_duration', sa.Float(), nullable=True, comment='Delta moving time in seconds compared to baseline'),
    sa.Column('delta_duration_pct', sa.Float(), nullable=True, comment='Delta moving time percentage compared to baseline'),
    sa.Column('delta_elevation_gain', sa.Float(), nullable=True, comment='Delta elevation gain compared to baseline'),
    sa.Column('delta_elevation_gain_pct', sa.Float(), nullable=True, comment='Delta elevation gain percentage compared to baseline'),
    sa.Column('delta_elevation_loss', sa.Float(), nullable=True, comment='Delta elevation loss compared to baseline'),
    sa.Column('delta_elevation_loss_pct', sa.Float(), nullable=True, comment='Delta elevation loss percentage compared to baseline'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Delta record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Delta record last update timestamp'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id']),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_delta_records_activity_id'), 'activity_delta_records', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_delta_records_user_id'), 'activity_delta_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_delta_records_activity_type_id'), 'activity_delta_records', ['activity_type_id'], unique=False)
    op.create_index(op.f('ix_activity_delta_records_category_id'), 'activity_delta_records', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_delta_records_category_id'), table_name='activity_delta_records')
    op.drop_index(op.f('ix_activity_delta_records_activity_type_id'), table_name='activity_delta_records')
    op.drop_index(op.f('ix_activity_delta_records_user_id'), table_name='activity_delta_records')
    op.drop_index(op.f('ix_activity_delta_records_activity_id'), table_name='activity_delta_records')
    op.drop_table('activity_delta_records')
    op.drop_index(op.f('ix_activity_ai_insights_activity_id'), table_name='activity_ai_insights')
    op.drop_table('activity_ai_insights')
    op.drop_index(op.f('ix_user_activity_stats_category_id'), table_name='user_activity_stats')
    op.drop_index(op.f('ix_user_activity_stats_activity_type_id'), table_name='user_activity_stats')
    op.drop_index(op.f('ix_user_activity_stats_user_id'), table_name='user_activity_stats')
    op.drop_table('user_activity_stats')
    op.drop_index(op.f('ix_user_category_rules_user_id'), table_name='user_category_rules')
    op.drop_index(op.f('ix_user_category_rules_category_id'), table_name='user_category_rules')
    op.drop_index(op.f('ix_user_category_rules_activity_type_id'), table_name='user_category_rules')
    op.drop_table('user_category_rules')
    op.drop_index(op.f('ix_activity_types_name'), table_name='activity_types')
    op.drop_table('activity_types')
    op.drop_index(op.f('ix_activity_categories_name'), table_name='activity_categories')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
