"""v0.16.6 migration

Revision ID: 215d794b3041
Revises: da1a7a9cf8ac
Create Date: 2026-01-11 22:35:17.646195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "215d794b3041"
down_revision: Union[str, None] = "da1a7a9cf8ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_privacy_settings_user_id"), table_name="users_privacy_settings"
    )
    op.create_index(
        op.f("ix_users_privacy_settings_user_id"),
        "users_privacy_settings",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_privacy_settings_user_id"), table_name="users_privacy_settings"
    )
    op.create_index(
        op.f("ix_users_privacy_settings_user_id"),
        "users_privacy_settings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
